"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "gu";

const translations = {
  en: {
    exhibitions: "Expos",
    about: "About Us",
    contact: "Contact Us",
    home: "Go to home",
    primaryNavigation: "Primary navigation",
    mobileNavigation: "Mobile navigation",
    switchToGujarati: "Switch to Gujarati",
    switchToEnglish: "Switch to English",
    mobileContact: "Contact us",
    openMenu: "Open menu",
    communityImagePlaceholder: "Community image placeholder",
    registerNow: "Register now",
    activeExhibitions: "Active Expos",
    liveNow: "Live now",
    open: "Open",
    openForRegistration: "Open for registration",
    registrationFee: "Registration fee",
    slotsLeft: "slots left",
    spotsAvailable: "spots available",
    register: "Register now",
    eventsUnavailable: "Expos are temporarily unavailable.",
    eventsUnavailableDescription: "Please try again in a moment.",
    moreBeautyMoments: "More beauty moments are coming.",
    noEvents: "There are no expos open for registration right now.",
    aboutHeading: "Beauty. Quality. Wholesale.",
    aboutBody: "Soft Shine Cosmetic is a beauty and makeup products wholesale business dedicated to bringing quality beauty products to retailers, salons, makeup artists, beauty professionals, resellers, and businesses.",
    aboutSupport: "We focus on providing a diverse range of beauty and cosmetic products with a strong commitment to quality, reliability, and customer satisfaction.",
    beautyProducts: "Beauty Products",
    beautyProductsDescription: "A thoughtful range for every professional kit.",
    makeup: "Makeup",
    skincare: "Skincare",
    nailCare: "Nail Care",
    hairBeauty: "Hair & Beauty",
    beautyAccessories: "Beauty Accessories",
    professionalCosmetics: "Professional Cosmetics",
    call: "Call",
    whatsapp: "WhatsApp",
    required: "required",
    wholesaleSupply: "Wholesale Supply",
    wholesaleSupplyDescription: "A dependable partner for growing businesses.",
    qualityFocused: "Quality Focused",
    qualityFocusedDescription: "Products chosen with care and clarity.",
    trustedPartnership: "Trusted Partnership",
    trustedPartnershipDescription: "Long-term relationships, not quick transactions.",
    beautyEveryDetail: "Beauty, in every detail.",
    promise: "Our Promise",
    promiseDescription: "We believe beauty businesses deserve quality products, reliable service, and a wholesale partner they can trust.",
    qualityFirst: "Quality First",
    thoughtfulSourcing: "Thoughtful sourcing.",
    reliableSupply: "Reliable Supply",
    readyForBusiness: "Ready for business.",
    customerFocus: "Customer Focus",
    hereLongTerm: "Here for the long term.",
    connectingCommunity: "Connecting the Beauty Community",
    connectingDescription: "Soft Shine Cosmetic also brings beauty professionals, retailers, brands, and customers together through beauty expos and industry events.",
    exploreExhibitions: "Explore expos",
    getInTouch: "Get In Touch",
    name: "Name",
    phone: "Phone",
    email: "Email",
    message: "Message",
    sendMessage: "Send message",
    sending: "Sending…",
    openGoogleMaps: "Open in Google Maps",
    explore: "Explore",
    softShine: "Soft Shine",
    softShineDescription: "Beauty and makeup products wholesale for retailers, salons, makeup artists, and beauty businesses.",
    footerDescription: "Beauty & Makeup Products Wholesale",
    adminPortal: "Admin portal",
    allRights: "All rights reserved.",
    privacyTerms: "Privacy · Terms & Conditions",
    close: "Close",
    backToExhibitions: "Back to expos",
    backToEvent: "Back to event",
    yourDetails: "Your details",
    reservePlace: "Reserve your place.",
    completeDetails: "Complete your details, then continue to secure payment for",
    exclusiveVisitors: "These expos are exclusively for female visitors.",
    fullName: "Full name",
    yourFullName: "Your full name",
    phoneNumber: "Phone number",
    mobilePlaceholder: "10-digit mobile number",
    emailAddress: "Email address",
    city: "City",
    yourCity: "Your city",
    category: "Category",
    parlourOwner: "Parlour Owner",
    others: "Others",
    gender: "Gender",
    female: "Female",
    termsAgree: "I agree to the Terms & Conditions and understand that my place is confirmed after successful payment.",
    pricingPayment: "Pricing & Payment",
    totalAmount: "Total amount",
    securePayment: "Secure payment via Razorpay",
    preparingPayment: "Preparing payment…",
    payAndRegister: "Pay and Register",
    cancelRegistration: "Cancel registration",
    openingCheckout: "Opening secure checkout",
    paymentSaved: "Your details are saved for",
    completePayment: "Complete payment in the Razorpay window to confirm your place.",
    pendingRegistration: "Pending registration",
    backToRegistration: "Back to registration",
    paymentUnsuccessful: "Payment unsuccessful",
    paymentCancelled: "Payment cancelled",
    notConfirmed: "Your registration has not been confirmed.",
    paymentInterrupted: "Something interrupted the payment. You can try again with the same details.",
    razorpayClosed: "The Razorpay window was closed before payment was completed.",
    tryAgain: "Try again",
    paymentVerified: "Payment verified",
    registrationSuccessful: "Registration successful.",
    ticketInstruction: "Your place is confirmed. Download the ticket PDF and carry it to the expo.",
    paid: "Paid",
    attendee: "Attendee",
    registrationId: "Registration ID",
    date: "Date",
    time: "Time",
    venue: "Venue",
    amountPaid: "Amount paid",
    downloadTicketPdf: "Download ticket PDF",
    creatingTicketPdf: "Creating ticket PDF…",
    presentedWith: "Presented with",
    sponsors: "Our Sponsors",
    sponsorsDescription: "Proudly supported by the brands making this beauty community possible.",
    somnathBeautyExpo: "Somnath Beauty Expo",
    eventShortDescription: "Beauty, cosmetics and professional makeup discoveries for the women shaping the industry.",
    eventFullDescription: "A focused beauty and cosmetics expo for retailers, salons, makeup artists, resellers and beauty professionals.",
    eventTerms: "These expos are exclusively for female visitors. Please carry a valid photo ID.",
    kapishwarPartyplot: "Kapishwar Partyplot, Veraval",
    veravalGujarat: "Veraval, Gujarat",
    veraval: "Veraval",
    gujarat: "Gujarat",
    india: "India",
    dhruvinSolanki: "Dhruvin Solanki",
    govindSolanki: "Govind Solanki"
  },
  gu: {
    exhibitions: "એક્સ્પો",
    about: "અમારા વિશે",
    contact: "સંપર્ક કરો",
    home: "હોમ પેજ પર જાઓ",
    primaryNavigation: "મુખ્ય નેવિગેશન",
    mobileNavigation: "મોબાઇલ નેવિગેશન",
    switchToGujarati: "ગુજરાતીમાં બદલો",
    switchToEnglish: "અંગ્રેજીમાં બદલો",
    mobileContact: "સંપર્ક કરો",
    openMenu: "મેનુ ખોલો",
    communityImagePlaceholder: "સમુદાયની છબી માટે સ્થાન",
    registerNow: "હમણાં નોંધણી કરો",
    activeExhibitions: "ચાલુ એક્સ્પો",
    liveNow: "હમણાં ચાલુ",
    open: "ખુલ્લું",
    openForRegistration: "નોંધણી માટે ખુલ્લું",
    registrationFee: "નોંધણી ફી",
    slotsLeft: "સ્થાનો બાકી",
    spotsAvailable: "સ્થાનો ઉપલબ્ધ",
    register: "નોંધણી કરો",
    eventsUnavailable: "એક્સ્પો અત્યારે ઉપલબ્ધ નથી.",
    eventsUnavailableDescription: "થોડીવાર પછી ફરી પ્રયાસ કરો.",
    moreBeautyMoments: "સૌંદર્યની વધુ પળો ટૂંક સમયમાં આવી રહી છે.",
    noEvents: "હમણાં નોંધણી માટે કોઈ એક્સ્પો ખુલ્લો નથી.",
    aboutHeading: "સૌંદર્ય. ગુણવત્તા. જથ્થાબંધ.",
    aboutBody: "Soft Shine Cosmetic રિટેલર્સ, સલૂન્સ, મેકઅપ આર્ટિસ્ટ્સ, સૌંદર્ય નિષ્ણાતો, રિસેલર્સ અને વ્યવસાયો માટે ગુણવત્તાયુક્ત બ્યુટી પ્રોડક્ટ્સ પહોંચાડવા માટે સમર્પિત સૌંદર્ય અને મેકઅપ ઉત્પાદનોનો જથ્થાબંધ વ્યવસાય છે.",
    aboutSupport: "અમે ગુણવત્તા, વિશ્વસનીયતા અને ગ્રાહક સંતોષ માટે મજબૂત પ્રતિબદ્ધતા સાથે વિવિધ સૌંદર્ય અને કોસ્મેટિક ઉત્પાદનો પ્રદાન કરીએ છીએ.",
    beautyProducts: "સૌંદર્ય ઉત્પાદનો",
    beautyProductsDescription: "દરેક પ્રોફેશનલ કિટ માટે પસંદ કરેલી શ્રેણી.",
    makeup: "મેકઅપ",
    skincare: "સ્કિનકેર",
    nailCare: "નેલ કેર",
    hairBeauty: "હેર અને બ્યુટી",
    beautyAccessories: "બ્યુટી એસેસરીઝ",
    professionalCosmetics: "પ્રોફેશનલ કોસ્મેટિક્સ",
    call: "કૉલ કરો",
    whatsapp: "વોટ્સએપ",
    required: "ફરજિયાત",
    wholesaleSupply: "જથ્થાબંધ પુરવઠો",
    wholesaleSupplyDescription: "વિકસતા વ્યવસાયો માટે વિશ્વસનીય ભાગીદાર.",
    qualityFocused: "ગુણવત્તા પર ધ્યાન",
    qualityFocusedDescription: "કાળજી અને સ્પષ્ટતા સાથે પસંદ કરેલા ઉત્પાદનો.",
    trustedPartnership: "વિશ્વાસપૂર્ણ ભાગીદારી",
    trustedPartnershipDescription: "ઝડપી વ્યવહાર નહીં, લાંબા ગાળાના સંબંધો.",
    beautyEveryDetail: "દરેક વિગતોમાં સૌંદર્ય.",
    promise: "અમારું વચન",
    promiseDescription: "સૌંદર્ય વ્યવસાયોને ગુણવત્તાયુક્ત ઉત્પાદનો, વિશ્વસનીય સેવા અને ભરોસાપાત્ર જથ્થાબંધ ભાગીદાર મળવો જોઈએ.",
    qualityFirst: "ગુણવત્તા પ્રથમ",
    thoughtfulSourcing: "કાળજીપૂર્વક પસંદગી.",
    reliableSupply: "વિશ્વસનીય પુરવઠો",
    readyForBusiness: "વ્યવસાય માટે તૈયાર.",
    customerFocus: "ગ્રાહક કેન્દ્રિત",
    hereLongTerm: "લાંબા સમય માટે તમારી સાથે.",
    connectingCommunity: "સૌંદર્ય સમુદાયને જોડીએ",
    connectingDescription: "Soft Shine Cosmetic એક્સ્પો અને ઉદ્યોગ કાર્યક્રમો દ્વારા સૌંદર્ય પ્રોફેશનલ્સ, રિટેલર્સ, બ્રાન્ડ્સ અને ગ્રાહકોને પણ જોડે છે.",
    exploreExhibitions: "એક્સ્પો જુઓ",
    getInTouch: "સંપર્ક કરો",
    name: "નામ",
    phone: "ફોન",
    email: "ઇમેઇલ",
    message: "સંદેશ",
    sendMessage: "સંદેશ મોકલો",
    sending: "મોકલી રહ્યા છીએ…",
    openGoogleMaps: "Google Mapsમાં ખોલો",
    explore: "જુઓ",
    softShine: "Soft Shine",
    softShineDescription: "રિટેલર્સ, સલૂન્સ, મેકઅપ આર્ટિસ્ટ્સ અને સૌંદર્ય વ્યવસાયો માટે સૌંદર્ય અને મેકઅપ ઉત્પાદનોનો જથ્થાબંધ પુરવઠો.",
    footerDescription: "બ્યુટી અને મેકઅપ ઉત્પાદનોનો જથ્થાબંધ પુરવઠો",
    adminPortal: "એડમિન પોર્ટલ",
    allRights: "સર્વ અધિકારો સુરક્ષિત.",
    privacyTerms: "ગોપનીયતા · નિયમો અને શરતો",
    close: "બંધ કરો",
    backToExhibitions: "એક્સ્પો પર પાછા જાઓ",
    backToEvent: "ઇવેન્ટ પર પાછા જાઓ",
    yourDetails: "તમારી વિગતો",
    reservePlace: "તમારું સ્થાન અનામત રાખો.",
    completeDetails: "તમારી વિગતો ભરો અને પછી સુરક્ષિત ચુકવણી માટે આગળ વધો:",
    exclusiveVisitors: "આ એક્સ્પો ફક્ત મહિલા મુલાકાતીઓ માટે છે.",
    fullName: "પૂરું નામ",
    yourFullName: "તમારું પૂરું નામ",
    phoneNumber: "ફોન નંબર",
    mobilePlaceholder: "10 અંકનો મોબાઇલ નંબર",
    emailAddress: "ઇમેઇલ સરનામું",
    city: "શહેર",
    yourCity: "તમારું શહેર",
    category: "શ્રેણી",
    parlourOwner: "પાર્લર માલિક",
    others: "અન્ય",
    gender: "લિંગ",
    female: "મહિલા",
    termsAgree: "હું નિયમો અને શરતો સાથે સંમત છું અને સમજું છું કે સફળ ચુકવણી પછી જ મારું સ્થાન નિશ્ચિત થશે.",
    pricingPayment: "કિંમત અને ચુકવણી",
    totalAmount: "કુલ રકમ",
    securePayment: "Razorpay દ્વારા સુરક્ષિત ચુકવણી",
    preparingPayment: "ચુકવણી તૈયાર થઈ રહી છે…",
    payAndRegister: "ચુકવણી કરો અને નોંધણી કરો",
    cancelRegistration: "નોંધણી રદ કરો",
    openingCheckout: "સુરક્ષિત ચેકઆઉટ ખોલી રહ્યા છીએ",
    paymentSaved: "તમારી વિગતો આ માટે સાચવવામાં આવી છે:",
    completePayment: "તમારું સ્થાન નિશ્ચિત કરવા Razorpay વિન્ડોમાં ચુકવણી પૂર્ણ કરો.",
    pendingRegistration: "બાકી નોંધણી",
    backToRegistration: "નોંધણી પર પાછા જાઓ",
    paymentUnsuccessful: "ચુકવણી નિષ્ફળ",
    paymentCancelled: "ચુકવણી રદ",
    notConfirmed: "તમારી નોંધણીની પુષ્ટિ થઈ નથી.",
    paymentInterrupted: "ચુકવણીમાં વિક્ષેપ આવ્યો. તમે એ જ વિગતો સાથે ફરી પ્રયાસ કરી શકો છો.",
    razorpayClosed: "ચુકવણી પૂર્ણ થાય તે પહેલાં Razorpay વિન્ડો બંધ થઈ ગઈ.",
    tryAgain: "ફરી પ્રયાસ કરો",
    paymentVerified: "ચુકવણીની પુષ્ટિ થઈ",
    registrationSuccessful: "નોંધણી સફળ થઈ.",
    ticketInstruction: "તમારું સ્થાન નિશ્ચિત છે. ટિકિટ PDF ડાઉનલોડ કરીને એક્સ્પોમાં સાથે લાવો.",
    paid: "ચૂકવેલ",
    attendee: "મુલાકાતી",
    registrationId: "નોંધણી ID",
    date: "તારીખ",
    time: "સમય",
    venue: "સ્થળ",
    amountPaid: "ચૂકવેલી રકમ",
    downloadTicketPdf: "ટિકિટ PDF ડાઉનલોડ કરો",
    creatingTicketPdf: "ટિકિટ PDF બનાવી રહ્યા છીએ…",
    presentedWith: "ની સાથે રજૂઆત",
    sponsors: "અમારા સ્પોન્સર્સ",
    sponsorsDescription: "આ સૌંદર્ય સમુદાયને શક્ય બનાવતી બ્રાન્ડ્સનો અમને ગર્વ છે.",
    somnathBeautyExpo: "સોમનાથ બ્યુટી એક્સ્પો",
    eventShortDescription: "ઉદ્યોગને આગળ વધારતી મહિલાઓ માટે બ્યુટી, કોસ્મેટિક્સ અને પ્રોફેશનલ મેકઅપની નવી શોધ.",
    eventFullDescription: "રિટેલર્સ, સલૂન્સ, મેકઅપ આર્ટિસ્ટ્સ, રિસેલર્સ અને સૌંદર્ય નિષ્ણાતો માટે કેન્દ્રિત બ્યુટી અને કોસ્મેટિક્સ એક્સ્પો.",
    eventTerms: "આ એક્સ્પો ફક્ત મહિલા મુલાકાતીઓ માટે છે. કૃપા કરીને માન્ય ફોટો ID સાથે લાવો.",
    kapishwarPartyplot: "કપિશ્વર પાર્ટીપ્લોટ, વેરાવળ",
    veravalGujarat: "વેરાવળ, ગુજરાત",
    veraval: "વેરાવળ",
    gujarat: "ગુજરાત",
    india: "ભારત",
    dhruvinSolanki: "ધ્રુવિન સોલંકી",
    govindSolanki: "ગોવિંદ સોલંકી"
  }
} as const;

export type TranslationKey = keyof typeof translations.en;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    document.documentElement.lang = language === "gu" ? "gu" : "en";
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translations[language][key] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider.");
  return context;
}
